### ISSUE TITLE
TODO: 

### ISSUE THREAD

**Issue by manuvariego** [manuvariego/DSW-BackEnd#4]
- [ ] Parameter 'localidad' has any type
- [ ] (localidad:any) nothing in common with parameter
- [ ] relacionar localidad y cochera y mostrar la localidad de cada cochera (se relaciona con los errores de arriba) 
- [ ] ver si necesitamos un uuid para el id, por lo del parseInt
- [ ] utilizar un idioma (estamos mezclando los dos, en algunos lados dice user otros usuario, etc) 
- [ ] no se deberia poder repetir el mismo usuario en la base de datos 
- [x] ordenar carpetas en (controllers, entities, y routes)
- [x] borrar archivos no utiles a nuestro proyecto
